name: Keep Chat Platform Alive

on:
  schedule:
    # Run every 12 minutes (offset from other services)
    - cron: '*/12 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Ping Health Endpoint
      run: |
        echo "Pinging chat platform health endpoint..."
        response=$(curl -s -o /dev/null -w "%{http_code}" https://scalable-chat-platform.onrender.com/health)
        
        if [ $response -eq 200 ]; then
          echo "✅ Health check successful (HTTP $response)"
          
          # Get and display the health response
          health_data=$(curl -s https://scalable-chat-platform.onrender.com/health)
          echo "Health data: $health_data"
          
        else
          echo "❌ Health check failed (HTTP $response)"
          exit 1
        fi
        
    - name: Log Timestamp
      run: |
        echo "Keep-alive ping completed at: $(date -u)"
        echo "Next scheduled run in 12 minutes"